### ISSUE TITLE
Need for example of parallel_plot

### ISSUE THREAD

**Issue by Popsama** [jraine/parallel-coordinates-plot-dataframe#2]
Hi, 
I think it is an amazing function to plot parallel coordinates plots in Python. 
However, when I went through the source code of the parallel_plot function 
I found it is hard to understand the arguments like df, cols, and rank_attr.
Could you please add an example code for how to apply this function.
Thank you very much!

**Comment by marcosfelt** [comment]
Here's an example:

```python
# Get some data
from sklearn.datasets import fetch_california_housing
housing = fetch_california_housing()
df = pd.DataFrame(housing.data, columns=housing.feature_names)
df["price"] = housing.target

# Make plot
_ = parallel_plot(df.iloc[:50], cols=housing.feature_names[:3], rank_attr="price", curved=True)
```

![image](https://user-images.githubusercontent.com/25933639/223693026-7eec902b-50b6-4dab-ad24-c51876e186f7.png)

Also, the white boxes can be removed by deleting these lines:

https://github.com/jraine/parallel-coordinates-plot-dataframe/blob/983f421509f642b6e72e05a9f7051224e64082d3/parallel_plot.py#L83-L84

**Comment by Popsama** [comment]
Thanks a lot！ Have a nice day.
